name: LobbySystem
version: '${project.version}'
main: Main.LobbySystem
author: 'Dustin_284'
api-version: 1.19
commands:
  setspawn:
    description: Set the lobby spawn
    permission: lobbysystem.setspawn
    usage: /setspawn
  spawn:
    description: Teleport to the lobby spawn
  build:
    description: Toggle build mode
    permission: lobbysystem.build
  coins:
    description: Show your coins
  stats:
    description: Show your stats
  perks:
    description: Show your perks
  fly:
    description: Toggle fly mode
    permission: lobbysystem.perks.fly
  playtime:
    description: Show your playtime
  ip:
    description: Show the server ip
  dailyreward:
    description: Claim your daily reward
  shop:
    description: Open the shop